import 'dotenv/config';
import assert from 'node:assert/strict';
import test from 'node:test';

if (!process.env.DATABASE_URL) {
  test('Refund execution database matrix', { skip: 'DATABASE_URL is not configured' }, () => {});
} else {
  const [{ PrismaPg }, { PrismaClient }, { acceptQuickOffer }, { createQuickOffer }, { createPaymentAttempt }, { confirmPaymentAttempt }, { startMissionExecution }, { cancelQuickMission }, { createRefundExecution }, { confirmRefundExecution }, { failRefundExecution }, { getRefundDetails }, createService, confirmService, failService, readService] = await Promise.all([
    import('@prisma/adapter-pg'), import('@prisma/client'), import('../quick-offers/accept-quick-offer.ts'), import('../quick-offers/create-quick-offer.ts'), import('../payments/create-payment-attempt.ts'), import('../payments/confirm-payment-attempt.ts'), import('../missions/start-mission-execution.ts'), import('../missions/cancel-quick-mission.ts'), import('./create-refund-execution.ts'), import('./confirm-refund-execution.ts'), import('./fail-refund-execution.ts'), import('./get-refund-details.ts'), import('./create-refund-execution.ts'), import('./confirm-refund-execution.ts'), import('./fail-refund-execution.ts'), import('./get-refund-details.ts'),
  ]);
  const prisma = new PrismaClient({ adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL }) });
  const users = []; const connections = []; let sequence = 0;
  const customerActor = (u) => ({ userId: u.id, role: 'CUSTOMER', accountStatus: u.accountStatus });
  const relaisActor = (u) => ({ userId: u.id, role: 'RELAIS', accountStatus: u.accountStatus, relaisEligibility: 'APPROVED' });
  const adminActor = (u) => ({ userId: u.id, role: 'ADMIN', accountStatus: u.accountStatus });
  const expectCode = (promise, C, code) => assert.rejects(promise, (e) => e instanceof C && e.code === code);
  async function fixture() {
    const customer = await prisma.user.create({ data: { role: 'CUSTOMER', phoneNumber: `+226741${String(Date.now() + sequence++).slice(-6)}`, phoneVerifiedAt: new Date(), customerProfile: { create: {} } } }); users.push(customer.id);
    const relais = await prisma.user.create({ data: { role: 'RELAIS', phoneNumber: `+226742${String(Date.now() + sequence++).slice(-6)}`, phoneVerifiedAt: new Date(), relaisProfile: { create: { eligibility: 'APPROVED', availability: 'UNAVAILABLE' } } } }); users.push(relais.id);
    const admin = await prisma.user.create({ data: { role: 'ADMIN' } }); users.push(admin.id);
    const connection = await prisma.connection.create({ data: { customerId: customer.id, requestKey: `3i-${Date.now()}-${sequence++}`, lifecycle: 'CONNECTED', connectedAt: new Date() } }); connections.push(connection.id);
    await prisma.connectionAssignment.create({ data: { connectionId: connection.id, relaisUserId: relais.id } }); await prisma.conversation.create({ data: { connectionId: connection.id } });
    const offer = await createQuickOffer({ actor: relaisActor(relais), connectionId: connection.id, amount: 2000, clientOfferId: `3i-offer-${sequence++}` }, prisma); const accepted = await acceptQuickOffer({ actor: customerActor(customer), quickOfferId: offer.offer.id }, prisma);
    const paymentAttempt = await createPaymentAttempt({ actor: customerActor(customer), paymentObligationId: accepted.paymentObligation.id, method: 'MOBILE_MONEY', provider: 'MANUAL', clientAttemptId: `3i-payment-${sequence++}` }, prisma); await confirmPaymentAttempt({ paymentAttemptId: paymentAttempt.attempt.id, confirmation: { source: 'PROVIDER', provider: 'MANUAL', externalReference: `3i-tx-${sequence++}`, confirmedAt: new Date(), confirmedAmount: 2000, currency: 'XOF' } }, prisma); await startMissionExecution({ actor: relaisActor(relais), missionId: accepted.mission.id }, prisma); await cancelQuickMission({ actor: customerActor(customer), missionId: accepted.mission.id }, prisma);
    const entitlement = await prisma.refundEntitlement.findUnique({ where: { missionId: accepted.mission.id } }); return { customer, relais, admin, connection, missionId: accepted.mission.id, entitlementId: entitlement.id, obligationId: accepted.paymentObligation.id };
  }
  async function cleanup() {
    if (connections.length) { await prisma.refundExecution.deleteMany({ where: { refundEntitlement: { mission: { connectionId: { in: connections } } } } }); await prisma.refundEntitlement.deleteMany({ where: { mission: { connectionId: { in: connections } } } }); await prisma.missionCancellation.deleteMany({ where: { mission: { connectionId: { in: connections } } } }); await prisma.completionAttempt.deleteMany({ where: { mission: { connectionId: { in: connections } } } }); await prisma.paymentAttempt.deleteMany({ where: { paymentObligation: { mission: { connectionId: { in: connections } } } } }); await prisma.paymentObligation.deleteMany({ where: { mission: { connectionId: { in: connections } } } }); await prisma.missionAssignment.deleteMany({ where: { mission: { connectionId: { in: connections } } } }); await prisma.mission.deleteMany({ where: { connectionId: { in: connections } } }); await prisma.quickOffer.deleteMany({ where: { connectionId: { in: connections } } }); await prisma.message.deleteMany({ where: { conversation: { connectionId: { in: connections } } } }); await prisma.connectionAssignment.deleteMany({ where: { connectionId: { in: connections } } }); await prisma.conversation.deleteMany({ where: { connectionId: { in: connections } } }); await prisma.connection.deleteMany({ where: { id: { in: connections } } }); }
    if (users.length) { await prisma.customerProfile.deleteMany({ where: { userId: { in: users } } }); await prisma.relaisProfile.deleteMany({ where: { userId: { in: users } } }); await prisma.user.deleteMany({ where: { id: { in: users } } }); } connections.length = 0; users.length = 0;
  }

  test('Admin creates PENDING execution from exact entitlement and confirms manual refund', async () => {
    try { const f = await fixture(); const created = await createRefundExecution({ actor: adminActor(f.admin), refundEntitlementId: f.entitlementId, method: 'MOBILE_MONEY', provider: 'ORANGE_MONEY', clientRefundId: 'refund-1' }, prisma); assert.equal(created.status, 'CREATED'); assert.equal(created.execution.status, 'PENDING'); assert.equal(created.execution.amount, 1000); assert.equal(created.execution.currency, 'XOF'); assert.equal(created.execution.destinationPhoneNumber, f.customer.phoneNumber); const confirmed = await confirmRefundExecution({ actor: adminActor(f.admin), refundExecutionId: created.execution.id, externalReference: 'OM-BF-83920481' }, prisma); assert.equal(confirmed.status, 'COMPLETED'); assert.equal(confirmed.execution.confirmationSource, 'MANUAL'); assert.equal(confirmed.execution.confirmedByUserId, f.admin.id); assert.ok(confirmed.execution.confirmedAt); const payment = await prisma.paymentObligation.findUnique({ where: { id: f.obligationId }, select: { status: true } }); const mission = await prisma.mission.findUnique({ where: { id: f.missionId }, select: { lifecycle: true } }); assert.equal(payment.status, 'PAID'); assert.equal(mission.lifecycle, 'CANCELLED'); } finally { await cleanup(); }
  });

  test('creation idempotency, active constraint, and authorization are enforced', async () => {
    try { const f = await fixture(); const input = { actor: adminActor(f.admin), refundEntitlementId: f.entitlementId, method: 'MOBILE_MONEY', provider: 'MOOV_MONEY', clientRefundId: 'same-refund' }; const first = await createRefundExecution(input, prisma); const existing = await createRefundExecution(input, prisma); assert.equal(existing.status, 'EXISTING'); assert.equal(existing.execution.id, first.execution.id); await expectCode(createRefundExecution({ ...input, provider: 'ORANGE_MONEY' }, prisma), createService.CreateRefundExecutionError, 'IDEMPOTENCY_CONFLICT'); await expectCode(createRefundExecution({ ...input, clientRefundId: 'other-refund' }, prisma), createService.CreateRefundExecutionError, 'ACTIVE_REFUND_EXECUTION_EXISTS'); await expectCode(createRefundExecution({ ...input, actor: customerActor(f.customer), clientRefundId: 'customer-refund' }, prisma), createService.CreateRefundExecutionError, 'UNAUTHORIZED'); } finally { await cleanup(); }
  });

  test('failed execution preserves entitlement and permits retry, while completed blocks retry', async () => {
    try { const f = await fixture(); const first = await createRefundExecution({ actor: adminActor(f.admin), refundEntitlementId: f.entitlementId, method: 'MOBILE_MONEY', provider: 'MANUAL', clientRefundId: 'failed-first' }, prisma); const failed = await failRefundExecution({ actor: adminActor(f.admin), refundExecutionId: first.execution.id, reason: 'Numéro invalide.' }, prisma); assert.equal(failed.status, 'FAILED'); const second = await createRefundExecution({ actor: adminActor(f.admin), refundEntitlementId: f.entitlementId, method: 'MOBILE_MONEY', provider: 'MANUAL', clientRefundId: 'retry-second' }, prisma); await confirmRefundExecution({ actor: adminActor(f.admin), refundExecutionId: second.execution.id, externalReference: 'MANUAL-TX-2' }, prisma); await expectCode(createRefundExecution({ actor: adminActor(f.admin), refundEntitlementId: f.entitlementId, method: 'MOBILE_MONEY', provider: 'MANUAL', clientRefundId: 'third' }, prisma), createService.CreateRefundExecutionError, 'REFUND_ALREADY_COMPLETED'); const entitlement = await prisma.refundEntitlement.findUnique({ where: { id: f.entitlementId }, select: { entitledAmount: true, currency: true, policyVersion: true } }); assert.deepEqual(entitlement, { entitledAmount: 1000, currency: 'XOF', policyVersion: 'QUICK_V1' }); } finally { await cleanup(); }
  });

  test('confirmation evidence is immutable and reads are role-scoped', async () => {
    try { const f = await fixture(); const execution = await createRefundExecution({ actor: adminActor(f.admin), refundEntitlementId: f.entitlementId, method: 'MOBILE_MONEY', provider: 'ORANGE_MONEY', clientRefundId: 'read-refund' }, prisma); const first = await confirmRefundExecution({ actor: adminActor(f.admin), refundExecutionId: execution.execution.id, externalReference: 'TX-UNIQUE-1' }, prisma); const again = await confirmRefundExecution({ actor: adminActor(f.admin), refundExecutionId: execution.execution.id, externalReference: 'TX-UNIQUE-1' }, prisma); assert.equal(again.status, 'ALREADY_COMPLETED'); assert.equal(again.execution.confirmedAt?.getTime(), first.execution.confirmedAt?.getTime()); await expectCode(confirmRefundExecution({ actor: adminActor(f.admin), refundExecutionId: execution.execution.id, externalReference: 'TX-DIFFERENT' }, prisma), confirmService.ConfirmRefundExecutionError, 'CONFIRMATION_CONFLICT'); const customerRead = await getRefundDetails({ actor: customerActor(f.customer), refundEntitlementId: f.entitlementId }, prisma); assert.equal(customerRead.executions[0].destinationPhoneNumber, null); await expectCode(getRefundDetails({ actor: relaisActor(f.relais), refundEntitlementId: f.entitlementId }, prisma), readService.GetRefundDetailsError, 'UNAUTHORIZED'); const adminRead = await getRefundDetails({ actor: adminActor(f.admin), refundEntitlementId: f.entitlementId }, prisma); assert.equal(adminRead.executions[0].destinationPhoneNumber, f.customer.phoneNumber); } finally { await cleanup(); }
  });

  test.after(async () => { await cleanup(); await prisma.$disconnect(); });
}
