import 'dotenv/config';
import assert from 'node:assert/strict';
import test from 'node:test';

if (!process.env.DATABASE_URL) {
  test('Mission feedback database matrix', { skip: 'DATABASE_URL is not configured' }, () => {});
} else {
  const [{ PrismaPg }, { PrismaClient }, { acceptQuickOffer }, { createQuickOffer }, { createPaymentAttempt }, { confirmPaymentAttempt }, { startMissionExecution }, { proposeMissionCompletion }, { confirmMissionCompletion }, { submitMissionFeedback }, submitService, { getMissionFeedback }, readService] = await Promise.all([
    import('@prisma/adapter-pg'), import('@prisma/client'), import('../quick-offers/accept-quick-offer.ts'), import('../quick-offers/create-quick-offer.ts'), import('../payments/create-payment-attempt.ts'), import('../payments/confirm-payment-attempt.ts'), import('../missions/start-mission-execution.ts'), import('../missions/propose-mission-completion.ts'), import('../missions/confirm-mission-completion.ts'), import('./submit-mission-feedback.ts'), import('./submit-mission-feedback.ts'), import('./get-mission-feedback.ts'), import('./get-mission-feedback.ts'),
  ]);
  const prisma = new PrismaClient({ adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL }) });
  const users = []; const connections = []; let sequence = 0;
  const customerActor = (u) => ({ userId: u.id, role: 'CUSTOMER', accountStatus: u.accountStatus });
  const relaisActor = (u) => ({ userId: u.id, role: 'RELAIS', accountStatus: u.accountStatus, relaisEligibility: 'REVOKED' });
  const adminActor = (u) => ({ userId: u.id, role: 'ADMIN', accountStatus: u.accountStatus });
  const expectCode = (promise, C, code) => assert.rejects(promise, (e) => e instanceof C && e.code === code);
  async function fixture() {
    const customer = await prisma.user.create({ data: { role: 'CUSTOMER', phoneNumber: `+226751${String(Date.now() + sequence++).slice(-6)}`, phoneVerifiedAt: new Date(), customerProfile: { create: {} } } }); users.push(customer.id);
    const relais = await prisma.user.create({ data: { role: 'RELAIS', phoneNumber: `+226752${String(Date.now() + sequence++).slice(-6)}`, phoneVerifiedAt: new Date(), relaisProfile: { create: { eligibility: 'APPROVED', availability: 'UNAVAILABLE' } } } }); users.push(relais.id);
    const otherCustomer = await prisma.user.create({ data: { role: 'CUSTOMER', customerProfile: { create: {} } } }); users.push(otherCustomer.id);
    const otherRelais = await prisma.user.create({ data: { role: 'RELAIS', relaisProfile: { create: { eligibility: 'APPROVED' } } } }); users.push(otherRelais.id);
    const admin = await prisma.user.create({ data: { role: 'ADMIN' } }); users.push(admin.id);
    const connection = await prisma.connection.create({ data: { customerId: customer.id, requestKey: `3j-${Date.now()}-${sequence++}`, lifecycle: 'CONNECTED', connectedAt: new Date() } }); connections.push(connection.id);
    await prisma.connectionAssignment.create({ data: { connectionId: connection.id, relaisUserId: relais.id } }); await prisma.conversation.create({ data: { connectionId: connection.id } });
    const offer = await createQuickOffer({ actor: { userId: relais.id, role: 'RELAIS', accountStatus: relais.accountStatus, relaisEligibility: 'APPROVED' }, connectionId: connection.id, amount: 2000, clientOfferId: `3j-offer-${sequence++}` }, prisma); const accepted = await acceptQuickOffer({ actor: customerActor(customer), quickOfferId: offer.offer.id }, prisma);
    const paymentAttempt = await createPaymentAttempt({ actor: customerActor(customer), paymentObligationId: accepted.paymentObligation.id, method: 'MOBILE_MONEY', provider: 'MANUAL', clientAttemptId: `3j-payment-${sequence++}` }, prisma); await confirmPaymentAttempt({ paymentAttemptId: paymentAttempt.attempt.id, confirmation: { source: 'PROVIDER', provider: 'MANUAL', externalReference: `3j-tx-${sequence++}`, confirmedAt: new Date(), confirmedAmount: 2000, currency: 'XOF' } }, prisma); await startMissionExecution({ actor: { userId: relais.id, role: 'RELAIS', accountStatus: relais.accountStatus, relaisEligibility: 'APPROVED' }, missionId: accepted.mission.id }, prisma); const proposal = await proposeMissionCompletion({ actor: { userId: relais.id, role: 'RELAIS', accountStatus: relais.accountStatus, relaisEligibility: 'APPROVED' }, missionId: accepted.mission.id, summary: 'Mission terminée.', clientCompletionId: '3j-completion' }, prisma); await confirmMissionCompletion({ actor: customerActor(customer), completionAttemptId: proposal.attempt.id }, prisma);
    await prisma.relaisProfile.update({ where: { userId: relais.id }, data: { eligibility: 'REVOKED', availability: 'UNAVAILABLE' } });
    return { customer, relais, otherCustomer, otherRelais, admin, connection, missionId: accepted.mission.id, obligationId: accepted.paymentObligation.id };
  }
  async function cleanup() {
    if (connections.length) { await prisma.missionFeedback.deleteMany({ where: { mission: { connectionId: { in: connections } } } }); await prisma.refundExecution.deleteMany({ where: { refundEntitlement: { mission: { connectionId: { in: connections } } } } }); await prisma.refundEntitlement.deleteMany({ where: { mission: { connectionId: { in: connections } } } }); await prisma.missionCancellation.deleteMany({ where: { mission: { connectionId: { in: connections } } } }); await prisma.completionAttempt.deleteMany({ where: { mission: { connectionId: { in: connections } } } }); await prisma.paymentAttempt.deleteMany({ where: { paymentObligation: { mission: { connectionId: { in: connections } } } } }); await prisma.paymentObligation.deleteMany({ where: { mission: { connectionId: { in: connections } } } }); await prisma.missionAssignment.deleteMany({ where: { mission: { connectionId: { in: connections } } } }); await prisma.mission.deleteMany({ where: { connectionId: { in: connections } } }); await prisma.quickOffer.deleteMany({ where: { connectionId: { in: connections } } }); await prisma.message.deleteMany({ where: { conversation: { connectionId: { in: connections } } } }); await prisma.connectionAssignment.deleteMany({ where: { connectionId: { in: connections } } }); await prisma.conversation.deleteMany({ where: { connectionId: { in: connections } } }); await prisma.connection.deleteMany({ where: { id: { in: connections } } }); }
    if (users.length) { await prisma.customerProfile.deleteMany({ where: { userId: { in: users } } }); await prisma.relaisProfile.deleteMany({ where: { userId: { in: users } } }); await prisma.user.deleteMany({ where: { id: { in: users } } }); } connections.length = 0; users.length = 0;
  }

  test('Customer and historical Relais can independently submit immutable feedback', async () => {
    try { const f = await fixture(); const customer = await submitMissionFeedback({ actor: customerActor(f.customer), missionId: f.missionId, rating: 5, comment: 'Très bonne expérience. Merci 🙏🏾', clientFeedbackId: 'customer-feedback' }, prisma); const relais = await submitMissionFeedback({ actor: relaisActor(f.relais), missionId: f.missionId, rating: 4, comment: 'Client respectueux.', clientFeedbackId: 'relais-feedback' }, prisma); assert.equal(customer.status, 'CREATED'); assert.equal(relais.status, 'CREATED'); assert.equal(customer.feedback.authorUserId, f.customer.id); assert.equal(customer.feedback.subjectUserId, f.relais.id); assert.equal(customer.feedback.direction, 'CUSTOMER_TO_RELAIS'); assert.equal(relais.feedback.authorUserId, f.relais.id); assert.equal(relais.feedback.subjectUserId, f.customer.id); assert.equal(relais.feedback.direction, 'RELAIS_TO_CUSTOMER'); assert.equal(relais.feedback.comment, 'Client respectueux.'); assert.equal(await prisma.missionFeedback.count({ where: { missionId: f.missionId } }), 2); } finally { await cleanup(); }
  });

  test('rating validation, idempotency, direction uniqueness, and concurrency are enforced', async () => {
    try { const f = await fixture(); await expectCode(submitMissionFeedback({ actor: customerActor(f.customer), missionId: f.missionId, rating: 4.5, clientFeedbackId: 'bad' }, prisma), submitService.SubmitMissionFeedbackError, 'INVALID_RATING'); await expectCode(submitMissionFeedback({ actor: customerActor(f.customer), missionId: f.missionId, rating: 6, clientFeedbackId: 'bad2' }, prisma), submitService.SubmitMissionFeedbackError, 'INVALID_RATING'); const input = { actor: customerActor(f.customer), missionId: f.missionId, rating: 5, comment: 'Excellent.', clientFeedbackId: 'same' }; const first = await submitMissionFeedback(input, prisma); const existing = await submitMissionFeedback(input, prisma); assert.equal(existing.status, 'EXISTING'); assert.equal(existing.feedback.id, first.feedback.id); await expectCode(submitMissionFeedback({ ...input, rating: 2 }, prisma), submitService.SubmitMissionFeedbackError, 'IDEMPOTENCY_CONFLICT'); await expectCode(submitMissionFeedback({ ...input, clientFeedbackId: 'different' }, prisma), submitService.SubmitMissionFeedbackError, 'FEEDBACK_ALREADY_SUBMITTED'); const duplicateInput = { actor: relaisActor(f.relais), missionId: f.missionId, rating: 4, clientFeedbackId: 'concurrent' }; const results = await Promise.all([submitMissionFeedback(duplicateInput, prisma), submitMissionFeedback(duplicateInput, prisma)]); assert.deepEqual(results.map((r) => r.status).sort(), ['CREATED', 'EXISTING']); } finally { await cleanup(); }
  });

  test('participant reads are blind to counterpart feedback while Admin sees both', async () => {
    try { const f = await fixture(); await submitMissionFeedback({ actor: customerActor(f.customer), missionId: f.missionId, rating: 5, clientFeedbackId: 'customer-read' }, prisma); await submitMissionFeedback({ actor: relaisActor(f.relais), missionId: f.missionId, rating: 4, clientFeedbackId: 'relais-read' }, prisma); const customerRead = await getMissionFeedback({ actor: customerActor(f.customer), missionId: f.missionId }, prisma); assert.equal(customerRead.myFeedback.rating, 5); assert.equal(customerRead.counterpartFeedback, null); const relaisRead = await getMissionFeedback({ actor: relaisActor(f.relais), missionId: f.missionId }, prisma); assert.equal(relaisRead.myFeedback.rating, 4); assert.equal(relaisRead.counterpartFeedback, null); const adminRead = await getMissionFeedback({ actor: adminActor(f.admin), missionId: f.missionId }, prisma); assert.equal(adminRead.feedback.length, 2); await expectCode(getMissionFeedback({ actor: customerActor(f.otherCustomer), missionId: f.missionId }, prisma), readService.GetMissionFeedbackError, 'UNAUTHORIZED'); } finally { await cleanup(); }
  });

  test('feedback is unavailable before completion and does not alter Mission or financial history', async () => {
    try { const f = await fixture(); const beforeMission = await prisma.mission.findUnique({ where: { id: f.missionId }, select: { lifecycle: true, completedAt: true, executionStartedAt: true } }); const beforePayment = await prisma.paymentObligation.findUnique({ where: { id: f.obligationId }, select: { status: true, amount: true } }); await prisma.mission.update({ where: { id: f.missionId }, data: { lifecycle: 'ACTIVE' } }); await expectCode(submitMissionFeedback({ actor: customerActor(f.customer), missionId: f.missionId, rating: 3, clientFeedbackId: 'not-yet' }, prisma), submitService.SubmitMissionFeedbackError, 'FEEDBACK_NOT_AVAILABLE'); await prisma.mission.update({ where: { id: f.missionId }, data: { lifecycle: 'COMPLETED' } }); const feedback = await prisma.missionFeedback.findMany({ where: { missionId: f.missionId } }); assert.equal(feedback.length, 0); assert.equal(beforeMission.lifecycle, 'COMPLETED'); assert.ok(beforeMission.completedAt); const result = await submitMissionFeedback({ actor: customerActor(f.customer), missionId: f.missionId, rating: 3, comment: '  Correct.  ', clientFeedbackId: 'preserve' }, prisma); assert.equal(result.feedback.comment, 'Correct.'); assert.deepEqual(await prisma.mission.findUnique({ where: { id: f.missionId }, select: { lifecycle: true, completedAt: true, executionStartedAt: true } }), beforeMission); assert.deepEqual(await prisma.paymentObligation.findUnique({ where: { id: f.obligationId }, select: { status: true, amount: true } }), beforePayment); await assert.rejects(prisma.mission.delete({ where: { id: f.missionId } }), /MissionFeedback|restrict|violat/i); } finally { await cleanup(); }
  });

  test.after(async () => { await cleanup(); await prisma.$disconnect(); });
}
